const ADJECTIVES = [
  "cloud-based",
  "blockchain",
  "Web 3.0",
  "responsive",
  "GDPR-compliant",
  "HIPAA-compliant",
  "high-performance",
  "dynamic-range",
  "socially-conscious",
  "ultra-HD",
  "eco-friendly",
  "green",
  "IOT-enabled",
  "plug-and-play",
  "enterprise",
  "organic",
  "free-range",
  "biomedical",
  "handheld",
  "free-to-play",
  "high-throughput",
  "A.I.",
  "B2B",
  "B2C",
  "bespoke",
  "pharmaceutical",
  "gigabit",
  "Uber for",
  "Airbnb for",
  "Tinder for",
  "augmented reality",
  "quantum",
];
const NOUNS = [
  "funeral systems",
  "solutions",
  "sprockets",
  "widgets",
  "information systems",
  "board games",
  "tools",
  "hardware",
  "software",
  "consulting services",
  "devices",
  "platforms",
  "vehicles",
  "cars",
  "weapons",
  "cameras",
  "furniture",
  "juice pressers",
  "blenders",
  "jackets",
  "sunglasses",
  "Bluetooth speakers",
  "fitness trackers",
  "VR headsets",
  "cannabis",
  "banking",
  "scooter",
  "gene editing",
  "networking services",
  "social networks",
  "hoodies",
  "marketplaces",
  "chatbots",
];
const TRAILERS = [
  "",
  "",
  "",
  " as a service",
  " on demand",
  " delivery",
  " for millennials",
  " powered by ML",
];
export default function generateProductName() {
  const randomAdjective = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)];
  const randomNoun = NOUNS[Math.floor(Math.random() * NOUNS.length)];
  const randomTrailer = TRAILERS[Math.floor(Math.random() * TRAILERS.length)];
  return `${randomAdjective} ${randomNoun}${randomTrailer}`;
}
